// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Greet.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet {
  public static partial class FooService
  {
    static readonly string __ServiceName = "Greet.FooService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData> __Marshaller_Greet_RequestData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Marshaller_Greet_ResponseData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Method_SayHi = new grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHi",
        __Marshaller_Greet_RequestData,
        __Marshaller_Greet_ResponseData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Method_SayHiServerStreaming = new grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SayHiServerStreaming",
        __Marshaller_Greet_RequestData,
        __Marshaller_Greet_ResponseData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Method_SayHiClientStreaming = new grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SayHiClientStreaming",
        __Marshaller_Greet_RequestData,
        __Marshaller_Greet_ResponseData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Method_SayHiDuplex = new grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SayHiDuplex",
        __Marshaller_Greet_RequestData,
        __Marshaller_Greet_ResponseData);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.GreetReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of FooService</summary>
    [grpc::BindServiceMethod(typeof(FooService), "BindService")]
    public abstract partial class FooServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHi(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SayHiServerStreaming(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::IServerStreamWriter<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHiClientStreaming(grpc::IAsyncStreamReader<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SayHiDuplex(grpc::IAsyncStreamReader<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData> requestStream, grpc::IServerStreamWriter<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for FooService</summary>
    public partial class FooServiceClient : grpc::ClientBase<FooServiceClient>
    {
      /// <summary>Creates a new client for FooService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public FooServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for FooService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public FooServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected FooServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected FooServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData SayHi(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHi(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData SayHi(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHi, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHiAsync(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHiAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHiAsync(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHi, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHiServerStreaming(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHiServerStreaming(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHiServerStreaming(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SayHiServerStreaming, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHiClientStreaming(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHiClientStreaming(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHiClientStreaming(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SayHiClientStreaming, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHiDuplex(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHiDuplex(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHiDuplex(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SayHiDuplex, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override FooServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new FooServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(FooServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHi, serviceImpl.SayHi)
          .AddMethod(__Method_SayHiServerStreaming, serviceImpl.SayHiServerStreaming)
          .AddMethod(__Method_SayHiClientStreaming, serviceImpl.SayHiClientStreaming)
          .AddMethod(__Method_SayHiDuplex, serviceImpl.SayHiDuplex).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, FooServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHi, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(serviceImpl.SayHi));
      serviceBinder.AddMethod(__Method_SayHiServerStreaming, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(serviceImpl.SayHiServerStreaming));
      serviceBinder.AddMethod(__Method_SayHiClientStreaming, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(serviceImpl.SayHiClientStreaming));
      serviceBinder.AddMethod(__Method_SayHiDuplex, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(serviceImpl.SayHiDuplex));
    }

  }
  public static partial class BarService
  {
    static readonly string __ServiceName = "Greet.BarService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData> __Marshaller_Greet_RequestData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Marshaller_Greet_ResponseData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Method_SayHello = new grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_Greet_RequestData,
        __Marshaller_Greet_ResponseData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Method_SayHelloServerStreaming = new grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SayHelloServerStreaming",
        __Marshaller_Greet_RequestData,
        __Marshaller_Greet_ResponseData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Method_SayHelloClientStreaming = new grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SayHelloClientStreaming",
        __Marshaller_Greet_RequestData,
        __Marshaller_Greet_ResponseData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> __Method_SayHelloDuplex = new grpc::Method<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "SayHelloDuplex",
        __Marshaller_Greet_RequestData,
        __Marshaller_Greet_ResponseData);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.GreetReflection.Descriptor.Services[1]; }
    }

    /// <summary>Base class for server-side implementations of BarService</summary>
    [grpc::BindServiceMethod(typeof(BarService), "BindService")]
    public abstract partial class BarServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHello(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SayHelloServerStreaming(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::IServerStreamWriter<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHelloClientStreaming(grpc::IAsyncStreamReader<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SayHelloDuplex(grpc::IAsyncStreamReader<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData> requestStream, grpc::IServerStreamWriter<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BarService</summary>
    public partial class BarServiceClient : grpc::ClientBase<BarServiceClient>
    {
      /// <summary>Creates a new client for BarService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public BarServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BarService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public BarServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected BarServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected BarServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData SayHello(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData SayHello(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHelloAsync(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHelloAsync(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHelloServerStreaming(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloServerStreaming(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHelloServerStreaming(global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SayHelloServerStreaming, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHelloClientStreaming(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloClientStreaming(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHelloClientStreaming(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SayHelloClientStreaming, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHelloDuplex(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloDuplex(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData> SayHelloDuplex(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_SayHelloDuplex, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override BarServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BarServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(BarServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello)
          .AddMethod(__Method_SayHelloServerStreaming, serviceImpl.SayHelloServerStreaming)
          .AddMethod(__Method_SayHelloClientStreaming, serviceImpl.SayHelloClientStreaming)
          .AddMethod(__Method_SayHelloDuplex, serviceImpl.SayHelloDuplex).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BarServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(serviceImpl.SayHello));
      serviceBinder.AddMethod(__Method_SayHelloServerStreaming, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(serviceImpl.SayHelloServerStreaming));
      serviceBinder.AddMethod(__Method_SayHelloClientStreaming, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(serviceImpl.SayHelloClientStreaming));
      serviceBinder.AddMethod(__Method_SayHelloDuplex, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.RequestData, global::FrameworkEase.Universal.X.gRPC.Tests.Proto.Greet.ResponseData>(serviceImpl.SayHelloDuplex));
    }

  }
}
#endregion
