// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.9
// source: Greet.proto

package Greet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FooService_SayHi_FullMethodName                = "/Greet.FooService/SayHi"
	FooService_SayHiServerStreaming_FullMethodName = "/Greet.FooService/SayHiServerStreaming"
	FooService_SayHiClientStreaming_FullMethodName = "/Greet.FooService/SayHiClientStreaming"
	FooService_SayHiDuplex_FullMethodName          = "/Greet.FooService/SayHiDuplex"
)

// FooServiceClient is the client API for FooService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FooServiceClient interface {
	SayHi(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (*ResponseData, error)
	SayHiServerStreaming(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseData], error)
	SayHiClientStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestData, ResponseData], error)
	SayHiDuplex(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestData, ResponseData], error)
}

type fooServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFooServiceClient(cc grpc.ClientConnInterface) FooServiceClient {
	return &fooServiceClient{cc}
}

func (c *fooServiceClient) SayHi(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (*ResponseData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseData)
	err := c.cc.Invoke(ctx, FooService_SayHi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fooServiceClient) SayHiServerStreaming(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FooService_ServiceDesc.Streams[0], FooService_SayHiServerStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestData, ResponseData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooService_SayHiServerStreamingClient = grpc.ServerStreamingClient[ResponseData]

func (c *fooServiceClient) SayHiClientStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestData, ResponseData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FooService_ServiceDesc.Streams[1], FooService_SayHiClientStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestData, ResponseData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooService_SayHiClientStreamingClient = grpc.ClientStreamingClient[RequestData, ResponseData]

func (c *fooServiceClient) SayHiDuplex(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestData, ResponseData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FooService_ServiceDesc.Streams[2], FooService_SayHiDuplex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestData, ResponseData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooService_SayHiDuplexClient = grpc.BidiStreamingClient[RequestData, ResponseData]

// FooServiceServer is the server API for FooService service.
// All implementations must embed UnimplementedFooServiceServer
// for forward compatibility.
type FooServiceServer interface {
	SayHi(context.Context, *RequestData) (*ResponseData, error)
	SayHiServerStreaming(*RequestData, grpc.ServerStreamingServer[ResponseData]) error
	SayHiClientStreaming(grpc.ClientStreamingServer[RequestData, ResponseData]) error
	SayHiDuplex(grpc.BidiStreamingServer[RequestData, ResponseData]) error
	mustEmbedUnimplementedFooServiceServer()
}

// UnimplementedFooServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFooServiceServer struct{}

func (UnimplementedFooServiceServer) SayHi(context.Context, *RequestData) (*ResponseData, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHi not implemented")
}
func (UnimplementedFooServiceServer) SayHiServerStreaming(*RequestData, grpc.ServerStreamingServer[ResponseData]) error {
	return status.Error(codes.Unimplemented, "method SayHiServerStreaming not implemented")
}
func (UnimplementedFooServiceServer) SayHiClientStreaming(grpc.ClientStreamingServer[RequestData, ResponseData]) error {
	return status.Error(codes.Unimplemented, "method SayHiClientStreaming not implemented")
}
func (UnimplementedFooServiceServer) SayHiDuplex(grpc.BidiStreamingServer[RequestData, ResponseData]) error {
	return status.Error(codes.Unimplemented, "method SayHiDuplex not implemented")
}
func (UnimplementedFooServiceServer) mustEmbedUnimplementedFooServiceServer() {}
func (UnimplementedFooServiceServer) testEmbeddedByValue()                    {}

// UnsafeFooServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FooServiceServer will
// result in compilation errors.
type UnsafeFooServiceServer interface {
	mustEmbedUnimplementedFooServiceServer()
}

func RegisterFooServiceServer(s grpc.ServiceRegistrar, srv FooServiceServer) {
	// If the following call panics, it indicates UnimplementedFooServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FooService_ServiceDesc, srv)
}

func _FooService_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FooServiceServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FooService_SayHi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FooServiceServer).SayHi(ctx, req.(*RequestData))
	}
	return interceptor(ctx, in, info, handler)
}

func _FooService_SayHiServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestData)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FooServiceServer).SayHiServerStreaming(m, &grpc.GenericServerStream[RequestData, ResponseData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooService_SayHiServerStreamingServer = grpc.ServerStreamingServer[ResponseData]

func _FooService_SayHiClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FooServiceServer).SayHiClientStreaming(&grpc.GenericServerStream[RequestData, ResponseData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooService_SayHiClientStreamingServer = grpc.ClientStreamingServer[RequestData, ResponseData]

func _FooService_SayHiDuplex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FooServiceServer).SayHiDuplex(&grpc.GenericServerStream[RequestData, ResponseData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FooService_SayHiDuplexServer = grpc.BidiStreamingServer[RequestData, ResponseData]

// FooService_ServiceDesc is the grpc.ServiceDesc for FooService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FooService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Greet.FooService",
	HandlerType: (*FooServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _FooService_SayHi_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHiServerStreaming",
			Handler:       _FooService_SayHiServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHiClientStreaming",
			Handler:       _FooService_SayHiClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHiDuplex",
			Handler:       _FooService_SayHiDuplex_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Greet.proto",
}

const (
	BarService_SayHello_FullMethodName                = "/Greet.BarService/SayHello"
	BarService_SayHelloServerStreaming_FullMethodName = "/Greet.BarService/SayHelloServerStreaming"
	BarService_SayHelloClientStreaming_FullMethodName = "/Greet.BarService/SayHelloClientStreaming"
	BarService_SayHelloDuplex_FullMethodName          = "/Greet.BarService/SayHelloDuplex"
)

// BarServiceClient is the client API for BarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BarServiceClient interface {
	SayHello(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (*ResponseData, error)
	SayHelloServerStreaming(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseData], error)
	SayHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestData, ResponseData], error)
	SayHelloDuplex(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestData, ResponseData], error)
}

type barServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBarServiceClient(cc grpc.ClientConnInterface) BarServiceClient {
	return &barServiceClient{cc}
}

func (c *barServiceClient) SayHello(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (*ResponseData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseData)
	err := c.cc.Invoke(ctx, BarService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barServiceClient) SayHelloServerStreaming(ctx context.Context, in *RequestData, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResponseData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BarService_ServiceDesc.Streams[0], BarService_SayHelloServerStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestData, ResponseData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BarService_SayHelloServerStreamingClient = grpc.ServerStreamingClient[ResponseData]

func (c *barServiceClient) SayHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[RequestData, ResponseData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BarService_ServiceDesc.Streams[1], BarService_SayHelloClientStreaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestData, ResponseData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BarService_SayHelloClientStreamingClient = grpc.ClientStreamingClient[RequestData, ResponseData]

func (c *barServiceClient) SayHelloDuplex(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RequestData, ResponseData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BarService_ServiceDesc.Streams[2], BarService_SayHelloDuplex_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RequestData, ResponseData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BarService_SayHelloDuplexClient = grpc.BidiStreamingClient[RequestData, ResponseData]

// BarServiceServer is the server API for BarService service.
// All implementations must embed UnimplementedBarServiceServer
// for forward compatibility.
type BarServiceServer interface {
	SayHello(context.Context, *RequestData) (*ResponseData, error)
	SayHelloServerStreaming(*RequestData, grpc.ServerStreamingServer[ResponseData]) error
	SayHelloClientStreaming(grpc.ClientStreamingServer[RequestData, ResponseData]) error
	SayHelloDuplex(grpc.BidiStreamingServer[RequestData, ResponseData]) error
	mustEmbedUnimplementedBarServiceServer()
}

// UnimplementedBarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBarServiceServer struct{}

func (UnimplementedBarServiceServer) SayHello(context.Context, *RequestData) (*ResponseData, error) {
	return nil, status.Error(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedBarServiceServer) SayHelloServerStreaming(*RequestData, grpc.ServerStreamingServer[ResponseData]) error {
	return status.Error(codes.Unimplemented, "method SayHelloServerStreaming not implemented")
}
func (UnimplementedBarServiceServer) SayHelloClientStreaming(grpc.ClientStreamingServer[RequestData, ResponseData]) error {
	return status.Error(codes.Unimplemented, "method SayHelloClientStreaming not implemented")
}
func (UnimplementedBarServiceServer) SayHelloDuplex(grpc.BidiStreamingServer[RequestData, ResponseData]) error {
	return status.Error(codes.Unimplemented, "method SayHelloDuplex not implemented")
}
func (UnimplementedBarServiceServer) mustEmbedUnimplementedBarServiceServer() {}
func (UnimplementedBarServiceServer) testEmbeddedByValue()                    {}

// UnsafeBarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BarServiceServer will
// result in compilation errors.
type UnsafeBarServiceServer interface {
	mustEmbedUnimplementedBarServiceServer()
}

func RegisterBarServiceServer(s grpc.ServiceRegistrar, srv BarServiceServer) {
	// If the following call panics, it indicates UnimplementedBarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BarService_ServiceDesc, srv)
}

func _BarService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BarServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BarService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BarServiceServer).SayHello(ctx, req.(*RequestData))
	}
	return interceptor(ctx, in, info, handler)
}

func _BarService_SayHelloServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestData)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BarServiceServer).SayHelloServerStreaming(m, &grpc.GenericServerStream[RequestData, ResponseData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BarService_SayHelloServerStreamingServer = grpc.ServerStreamingServer[ResponseData]

func _BarService_SayHelloClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BarServiceServer).SayHelloClientStreaming(&grpc.GenericServerStream[RequestData, ResponseData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BarService_SayHelloClientStreamingServer = grpc.ClientStreamingServer[RequestData, ResponseData]

func _BarService_SayHelloDuplex_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BarServiceServer).SayHelloDuplex(&grpc.GenericServerStream[RequestData, ResponseData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BarService_SayHelloDuplexServer = grpc.BidiStreamingServer[RequestData, ResponseData]

// BarService_ServiceDesc is the grpc.ServiceDesc for BarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Greet.BarService",
	HandlerType: (*BarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _BarService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloServerStreaming",
			Handler:       _BarService_SayHelloServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloClientStreaming",
			Handler:       _BarService_SayHelloClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloDuplex",
			Handler:       _BarService_SayHelloDuplex_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Greet.proto",
}
