// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: Greet.proto

package Greet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestData) Reset() {
	*x = RequestData{}
	mi := &file_Greet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestData) ProtoMessage() {}

func (x *RequestData) ProtoReflect() protoreflect.Message {
	mi := &file_Greet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestData.ProtoReflect.Descriptor instead.
func (*RequestData) Descriptor() ([]byte, []int) {
	return file_Greet_proto_rawDescGZIP(), []int{0}
}

func (x *RequestData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResponseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseData) Reset() {
	*x = ResponseData{}
	mi := &file_Greet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseData) ProtoMessage() {}

func (x *ResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_Greet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseData.ProtoReflect.Descriptor instead.
func (*ResponseData) Descriptor() ([]byte, []int) {
	return file_Greet_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_Greet_proto protoreflect.FileDescriptor

const file_Greet_proto_rawDesc = "" +
	"\n" +
	"\vGreet.proto\x12\x05Greet\"!\n" +
	"\vRequestData\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"(\n" +
	"\fResponseData\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage2\x80\x02\n" +
	"\n" +
	"FooService\x120\n" +
	"\x05SayHi\x12\x12.Greet.RequestData\x1a\x13.Greet.ResponseData\x12A\n" +
	"\x14SayHiServerStreaming\x12\x12.Greet.RequestData\x1a\x13.Greet.ResponseData0\x01\x12A\n" +
	"\x14SayHiClientStreaming\x12\x12.Greet.RequestData\x1a\x13.Greet.ResponseData(\x01\x12:\n" +
	"\vSayHiDuplex\x12\x12.Greet.RequestData\x1a\x13.Greet.ResponseData(\x010\x012\x8c\x02\n" +
	"\n" +
	"BarService\x123\n" +
	"\bSayHello\x12\x12.Greet.RequestData\x1a\x13.Greet.ResponseData\x12D\n" +
	"\x17SayHelloServerStreaming\x12\x12.Greet.RequestData\x1a\x13.Greet.ResponseData0\x01\x12D\n" +
	"\x17SayHelloClientStreaming\x12\x12.Greet.RequestData\x1a\x13.Greet.ResponseData(\x01\x12=\n" +
	"\x0eSayHelloDuplex\x12\x12.Greet.RequestData\x1a\x13.Greet.ResponseData(\x010\x01B<Z\a./Greet\xaa\x020FrameworkEase.Universal.X.gRPC.Tests.Proto.Greetb\x06proto3"

var (
	file_Greet_proto_rawDescOnce sync.Once
	file_Greet_proto_rawDescData []byte
)

func file_Greet_proto_rawDescGZIP() []byte {
	file_Greet_proto_rawDescOnce.Do(func() {
		file_Greet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Greet_proto_rawDesc), len(file_Greet_proto_rawDesc)))
	})
	return file_Greet_proto_rawDescData
}

var file_Greet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Greet_proto_goTypes = []any{
	(*RequestData)(nil),  // 0: Greet.RequestData
	(*ResponseData)(nil), // 1: Greet.ResponseData
}
var file_Greet_proto_depIdxs = []int32{
	0, // 0: Greet.FooService.SayHi:input_type -> Greet.RequestData
	0, // 1: Greet.FooService.SayHiServerStreaming:input_type -> Greet.RequestData
	0, // 2: Greet.FooService.SayHiClientStreaming:input_type -> Greet.RequestData
	0, // 3: Greet.FooService.SayHiDuplex:input_type -> Greet.RequestData
	0, // 4: Greet.BarService.SayHello:input_type -> Greet.RequestData
	0, // 5: Greet.BarService.SayHelloServerStreaming:input_type -> Greet.RequestData
	0, // 6: Greet.BarService.SayHelloClientStreaming:input_type -> Greet.RequestData
	0, // 7: Greet.BarService.SayHelloDuplex:input_type -> Greet.RequestData
	1, // 8: Greet.FooService.SayHi:output_type -> Greet.ResponseData
	1, // 9: Greet.FooService.SayHiServerStreaming:output_type -> Greet.ResponseData
	1, // 10: Greet.FooService.SayHiClientStreaming:output_type -> Greet.ResponseData
	1, // 11: Greet.FooService.SayHiDuplex:output_type -> Greet.ResponseData
	1, // 12: Greet.BarService.SayHello:output_type -> Greet.ResponseData
	1, // 13: Greet.BarService.SayHelloServerStreaming:output_type -> Greet.ResponseData
	1, // 14: Greet.BarService.SayHelloClientStreaming:output_type -> Greet.ResponseData
	1, // 15: Greet.BarService.SayHelloDuplex:output_type -> Greet.ResponseData
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Greet_proto_init() }
func file_Greet_proto_init() {
	if File_Greet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Greet_proto_rawDesc), len(file_Greet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_Greet_proto_goTypes,
		DependencyIndexes: file_Greet_proto_depIdxs,
		MessageInfos:      file_Greet_proto_msgTypes,
	}.Build()
	File_Greet_proto = out.File
	file_Greet_proto_goTypes = nil
	file_Greet_proto_depIdxs = nil
}
